"""initial schema

Revision ID: 86cc864bb842
Revises: 
Create Date: 2026-09-09 03:55:20.639962
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '86cc864bb842'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=32), nullable=False),
    sa.Column('request_xml', sa.Text(), nullable=True),
    sa.Column('response_xml', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_ledger', sa.String(length=255), nullable=False),
    sa.Column('bill_name', sa.String(length=128), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('opening_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pending_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('tally_guid', sa.String(length=64), nullable=True),
    sa.Column('tally_master_id', sa.String(length=32), nullable=True),
    sa.Column('tally_alter_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_ledger', 'bill_name', 'direction', name='uq_bill_identity')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bills_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_party_ledger'), ['party_ledger'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_tally_alter_id'), ['tally_alter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_tally_guid'), ['tally_guid'], unique=False)

    op.create_table('cost_centres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.String(length=255), nullable=False),
    sa.Column('tally_guid', sa.String(length=64), nullable=True),
    sa.Column('tally_master_id', sa.String(length=32), nullable=True),
    sa.Column('tally_alter_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_centres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_centres_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_cost_centres_tally_alter_id'), ['tally_alter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_centres_tally_guid'), ['tally_guid'], unique=False)

    op.create_table('godowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.String(length=255), nullable=False),
    sa.Column('tally_guid', sa.String(length=64), nullable=True),
    sa.Column('tally_master_id', sa.String(length=32), nullable=True),
    sa.Column('tally_alter_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('godowns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_godowns_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_godowns_tally_alter_id'), ['tally_alter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_godowns_tally_guid'), ['tally_guid'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.String(length=255), nullable=False),
    sa.Column('primary_group', sa.String(length=255), nullable=False),
    sa.Column('is_revenue', sa.Boolean(), nullable=False),
    sa.Column('is_deemed_positive', sa.Boolean(), nullable=False),
    sa.Column('affects_gross_profit', sa.Boolean(), nullable=False),
    sa.Column('tally_guid', sa.String(length=64), nullable=True),
    sa.Column('tally_master_id', sa.String(length=32), nullable=True),
    sa.Column('tally_alter_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_groups_tally_alter_id'), ['tally_alter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_tally_guid'), ['tally_guid'], unique=False)

    op.create_table('ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_group', sa.String(length=255), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('mailing_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('gst_registration_type', sa.String(length=32), nullable=True),
    sa.Column('is_bill_wise', sa.Boolean(), nullable=False),
    sa.Column('tally_guid', sa.String(length=64), nullable=True),
    sa.Column('tally_master_id', sa.String(length=32), nullable=True),
    sa.Column('tally_alter_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledgers_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_ledgers_parent_group'), ['parent_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledgers_tally_alter_id'), ['tally_alter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledgers_tally_guid'), ['tally_guid'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('hsn', sa.String(length=16), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('closing_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('closing_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tally_guid', sa.String(length=64), nullable=True),
    sa.Column('tally_master_id', sa.String(length=32), nullable=True),
    sa.Column('tally_alter_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_items_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_stock_items_tally_alter_id'), ['tally_alter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_items_tally_guid'), ['tally_guid'], unique=False)

    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('records_changed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voucher_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('validation_errors_json', sa.Text(), nullable=False),
    sa.Column('generated_xml', sa.Text(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('tally_voucher_number', sa.String(length=64), nullable=True),
    sa.Column('tally_guid', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('allow_duplicate', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voucher_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voucher_drafts_status'), ['status'], unique=False)

    op.create_table('voucher_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.String(length=255), nullable=False),
    sa.Column('tally_guid', sa.String(length=64), nullable=True),
    sa.Column('tally_master_id', sa.String(length=32), nullable=True),
    sa.Column('tally_alter_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voucher_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voucher_types_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_voucher_types_tally_alter_id'), ['tally_alter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voucher_types_tally_guid'), ['tally_guid'], unique=False)

    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(length=64), nullable=False),
    sa.Column('voucher_type', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('party_ledger', sa.String(length=255), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=False),
    sa.Column('remote_id', sa.String(length=64), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('tally_guid', sa.String(length=64), nullable=True),
    sa.Column('tally_master_id', sa.String(length=32), nullable=True),
    sa.Column('tally_alter_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vouchers_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vouchers_party_ledger'), ['party_ledger'], unique=False)
        batch_op.create_index(batch_op.f('ix_vouchers_remote_id'), ['remote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vouchers_tally_alter_id'), ['tally_alter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vouchers_tally_guid'), ['tally_guid'], unique=False)
        batch_op.create_index('ix_vouchers_type_date', ['voucher_type', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vouchers_voucher_number'), ['voucher_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_vouchers_voucher_type'), ['voucher_type'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('ocr_status', sa.String(length=16), nullable=False),
    sa.Column('ocr_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['voucher_drafts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_draft_id'), ['draft_id'], unique=False)

    op.create_table('voucher_inventory_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('stock_item', sa.String(length=255), nullable=False),
    sa.Column('godown', sa.String(length=255), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rate', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hsn', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voucher_inventory_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voucher_inventory_entries_voucher_id'), ['voucher_id'], unique=False)

    op.create_table('voucher_ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('ledger_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_deemed_positive', sa.Boolean(), nullable=False),
    sa.Column('cost_centre', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voucher_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voucher_ledger_entries_ledger_name'), ['ledger_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_voucher_ledger_entries_voucher_id'), ['voucher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voucher_ledger_entries_voucher_id'))
        batch_op.drop_index(batch_op.f('ix_voucher_ledger_entries_ledger_name'))

    op.drop_table('voucher_ledger_entries')
    with op.batch_alter_table('voucher_inventory_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voucher_inventory_entries_voucher_id'))

    op.drop_table('voucher_inventory_entries')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_draft_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vouchers_voucher_type'))
        batch_op.drop_index(batch_op.f('ix_vouchers_voucher_number'))
        batch_op.drop_index('ix_vouchers_type_date')
        batch_op.drop_index(batch_op.f('ix_vouchers_tally_guid'))
        batch_op.drop_index(batch_op.f('ix_vouchers_tally_alter_id'))
        batch_op.drop_index(batch_op.f('ix_vouchers_remote_id'))
        batch_op.drop_index(batch_op.f('ix_vouchers_party_ledger'))
        batch_op.drop_index(batch_op.f('ix_vouchers_date'))

    op.drop_table('vouchers')
    with op.batch_alter_table('voucher_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voucher_types_tally_guid'))
        batch_op.drop_index(batch_op.f('ix_voucher_types_tally_alter_id'))
        batch_op.drop_index(batch_op.f('ix_voucher_types_name'))

    op.drop_table('voucher_types')
    with op.batch_alter_table('voucher_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voucher_drafts_status'))

    op.drop_table('voucher_drafts')
    op.drop_table('sync_runs')
    with op.batch_alter_table('stock_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_items_tally_guid'))
        batch_op.drop_index(batch_op.f('ix_stock_items_tally_alter_id'))
        batch_op.drop_index(batch_op.f('ix_stock_items_name'))

    op.drop_table('stock_items')
    op.drop_table('settings')
    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledgers_tally_guid'))
        batch_op.drop_index(batch_op.f('ix_ledgers_tally_alter_id'))
        batch_op.drop_index(batch_op.f('ix_ledgers_parent_group'))
        batch_op.drop_index(batch_op.f('ix_ledgers_name'))

    op.drop_table('ledgers')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_tally_guid'))
        batch_op.drop_index(batch_op.f('ix_groups_tally_alter_id'))
        batch_op.drop_index(batch_op.f('ix_groups_name'))

    op.drop_table('groups')
    with op.batch_alter_table('godowns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_godowns_tally_guid'))
        batch_op.drop_index(batch_op.f('ix_godowns_tally_alter_id'))
        batch_op.drop_index(batch_op.f('ix_godowns_name'))

    op.drop_table('godowns')
    with op.batch_alter_table('cost_centres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_centres_tally_guid'))
        batch_op.drop_index(batch_op.f('ix_cost_centres_tally_alter_id'))
        batch_op.drop_index(batch_op.f('ix_cost_centres_name'))

    op.drop_table('cost_centres')
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_tally_guid'))
        batch_op.drop_index(batch_op.f('ix_bills_tally_alter_id'))
        batch_op.drop_index(batch_op.f('ix_bills_party_ledger'))
        batch_op.drop_index(batch_op.f('ix_bills_due_date'))
        batch_op.drop_index(batch_op.f('ix_bills_direction'))

    op.drop_table('bills')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
